package online.davisfamily.warehouse.sim.dsp.analysis.input;

public enum DspInputRejectionReason {
    MALFORMED_12N_MESSAGE,
    MISSING_ADAPTED_SOURCE,
    MISSING_ADAPTED_FULFILMENT,
    DUPLICATE_ADAPTED_SOURCE,
    DUPLICATE_ADAPTED_FULFILMENT,
    ADAPTED_SOURCE_FULFILMENT_MISMATCH,
    UNCLASSIFIED_CORRELATION_ANOMALY
}
